### ISSUE TITLE
Set up automated code reviews

### ISSUE THREAD

**Issue by sumeetjain** [omahacodeschool/sms-crm#48]
```yml
# .rubocop.yml
Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false
```

```yml
# .travis.yml

script:
- 'PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} bundle exec pronto run -f github_pr -c origin/master'
language: ruby
rvm:
  - 2.3.0
```

```yml
# .pronto.yml

all:
  exclude:
    - 'spec/**/*'
github:
  slug: omahacodeschool/repo-name
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
max_warnings: 150
verbose: false
```

```ruby
# Gemfile

gem 'pronto'
gem 'pronto-rubocop'
gem 'pronto-reek'
gem 'pronto-rails_best_practices'
```
